# Generated by Django 3.1.3 on 2020-11-14 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='set_day',
        ),
    ]
