# Generated by Django 3.1.3 on 2020-11-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201116_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_content',
            field=models.CharField(max_length=300),
        ),
    ]
