# Generated by Django 3.1.3 on 2020-11-16 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201116_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
