# Generated by Django 3.1.3 on 2020-11-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201116_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
