# Generated by Django 3.1.3 on 2020-11-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_review_review_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlist',
            old_name='order',
            new_name='order_number',
        ),
    ]
