# Generated by Django 3.1.3 on 2020-11-12 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=10)),
                ('item_name', models.CharField(max_length=10)),
                ('item_price', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biz_name', models.CharField(max_length=10)),
                ('biz_num', models.IntegerField()),
                ('biz_url', models.CharField(max_length=15, unique=True)),
                ('biz_insta', models.CharField(max_length=15, null=True)),
                ('biz_address', models.CharField(max_length=40, null=True)),
                ('biz_tel', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Today_lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_day', models.DateField()),
                ('quota', models.IntegerField()),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.allitem')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.store')),
            ],
        ),
        migrations.CreateModel(
            name='Store_set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openday', models.DateField()),
                ('opentime', models.TimeField()),
                ('pickuptime', models.TimeField(null=True)),
                ('notification', models.CharField(max_length=50, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.store')),
            ],
        ),
        migrations.AddField(
            model_name='allitem',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.store'),
        ),
    ]
