# Generated by Django 3.1.3 on 2020-11-15 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20201113_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today_lineup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.today_lineup')),
            ],
        ),
    ]
