# Generated by Django 3.1.3 on 2020-11-15 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
